name: CI

on:
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    build:
        name: Build and Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v4.1.0
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: .tool-versions
            - name: Install dependencies
              run: pnpm i --frozen-lockfile
            - name: Build with Astro
              run: pnpm astro build
            - name: Check Astro
              run: pnpm astro check
            - name: Check formatting
              run: pnpm prettier . --check
